export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL"
export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN"
export const SET_LAST_BREADCRUMB = "SET_LAST_BREADCRUMB"
export const LOGGED_IN_SUCCESSFULLY = "LOGGED_IN_SUCCESSFULLY"
