version: '3.9'

services:
  admin:
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_MODULE=admin
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
